# Generated by Django 4.2.13 on 2024-07-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="movieuser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("usernamename", models.CharField(max_length=30, null=True)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("firstname", models.CharField(max_length=25, null=True, unique=True)),
                ("lastname", models.CharField(max_length=10, null=True)),
                ("password", models.CharField(max_length=20, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
