# Generated by Django 4.2.13 on 2024-07-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movieuser",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="movieuser",
            name="profilepic",
            field=models.ImageField(default="media/noneimage.jpg", upload_to="media"),
        ),
        migrations.AlterField(
            model_name="movieuser",
            name="usernamename",
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
