# Generated by Django 4.2.13 on 2024-07-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movieuser_description_movieuser_profilepic_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movieuser",
            old_name="usernamename",
            new_name="username",
        ),
    ]
