# Generated by Django 4.2.13 on 2024-07-02 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_usernamename_movieuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='movielist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('poster', models.ImageField(upload_to='media')),
                ('description', models.CharField(max_length=200)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('actors', models.CharField(max_length=200)),
                ('trailerlink', models.URLField()),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('reviews', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.category')),
            ],
        ),
    ]
