# Generated by Django 4.2.13 on 2024-07-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movielist_addeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='Language',
            field=models.CharField(default='English', max_length=200),
        ),
    ]
